/*****************************************************************************
 *   @file      version_hw.h
 *   @brief     header indicating hardware version differences and firmware
 *              compatibility options
 *   @project   Project CETI
 *   @copyright Harvard University Wood Lab
 *   @authors   Michael Salino-Hugg, [TODO: Add other contributors here]
 *****************************************************************************/
// Version Date Description
// 3_1.0   03/13/25 Begin work, establish framework

#ifndef CETI_WHALE_TAG_VERSIONING_H
#define CETI_WHALE_TAG_VERSIONING_H

// Possible values for HW_VERSION, defined in makefile

#define HW_VERSION_NUCLEO_DEV 0
// Nucleo based dev setup to verify chip family 

#define HW_VERSION_3_1_0 1
// Inital spun v3 board


#define HW_VERSION_3_1_0_MSH 2 
// 3.1.0 with 16 MHz HSE XTal

#define HW_VERSION_3_2_0 3
// ***DONE*** BACKUP [LOCAL TO MATT PC DROPBOX SHARE]
// ***DONE** UPDATE HPF CAPACITORS ON ECG SECTION
// ***DONE***DISCONNECT I2C ON GPS
// ***DONE*** ZERO OHM JUMPER ON VHF ENABLE
// ***DONE*** FIX IMU X/Y ARROWS ON THE STM SIDE
// ***IS CORRECT AS IS*** ARRIBADA REVIEW - PGOOD SHOULD BE PSEL. PSEL AND EN OF TPS63900 DRIVEN BY ARGOS SMD WATCH CONTENTION WITH MCU
// ***DONE***ARRIBADA REVIEW - 100 nF CAP NOT NEEDED ON RESET
// ***DONE***MC/MSH 11/25/25 REVISIT ISOLATION OF 3.3V FEEDING ARGOS FROM OTHER DIGITAL SUPPLIES.  REVIEW APPLICATION NOTES FOR THE ARGOS MODULE.
// ***DONE*** MRC 05/13/25  REVIEW AOLDO APPLICATION FOR BACKUP BATTERY. CHECK BLOCK DIA FOR CONSISTENCY
// ***DONE*** MRC 5/23/25 CONSIDER CONVERTING TRACK/PAD INTFCS TO TEARDROP [ADDED TEARDROP ACROSS BOARD]
// ***DONE*** MC 8/5/25 CONSIDER PINGER ON/OFF CONTROL. CONCERN ABOUT NOISE COUPLING TO AUDIO
// ***FIXED*** MC 9/15/25  BLOCK DIA - NO GPIO CONN TO PINGER IN THIS ITERATION
// ***DONE*** MRC 5/27/25 CHECK FFC AMPACITY  [CONN IS RATED 0.5A, TYPICAL CABLE 1A.  3 PINS FOR VSYS, GOOD MARGIN, CURRENT SHOULD BE MUCH LESS; CHARGING DOESN'T GO THROUGH FFC]
// ***DONE*** MC 10/29/26 ADD PADS FOR ARGOS DEBUG
// ***DONE*** MC 1/27/26 DOUBLE CHECK ARGOS FOOTPRINT [PER ARRIBIDA, EVALUATE THIS BUILD]
// ***DONE*** MC 1/27/26 LABEL RF CONNECTORS WITH FUNCTION
// ***FIXED*** MC/MSH 11/25/25 CHECK PARTIAL POWER AROUND ARGOS. V_SAT OFF WHILE V_3.3 ON?? [POWER TO ARGOS ALWAYS PRESENT]
// ***FIXED*** MC/MSH/DV 12/09/25  FIX ARGOS FOOTPRINT SO PADS EXTEND OUT FURTHER BEYOND CASTELLATIONS
// ***FIXED*** JD 01/27/26  Z AXIS LABEL NEEDS ONE SIDE TO BE SIDE X
// ***FIXED*** MC 8/20/25 UPDATED HSE FOR 16 MHZ AND DEDICATED ADC CLK.  SEE 3.1 NOTES
// ***FIXED*** SG 7/2/25 ARGOS MODULE FOOTPRINT MIRRORED
// ***FIXED*** SG 7/2/25 CLARIFY SCHEMATIC CONNECTION FOR -5V ENABLE
// ***FIXED*** SG 7/2/25 HSE XO NEEDS PULLUP ON OE, SYMBOL PIN 3 INCORRECT
// ***FIXED*** MS 7/31/25 MECHANICAL INTERFERENCE AROUND DEPTH SENSOR  [MOVED THE INDUCTOR]
// ***FIXED*** MS 7/31/25 SPI CS FOR AUDIO/IMU NON-UNIQUE. CONNECT ADC CS TO PIN13 OF STM. SEE REWORK NOTES IN SLACK
// ***FIXED*** MS 8/19/25 ADD STM GPIO CONNECTION FOR IMU PS0/WAKE
// ***FIXED*** MC 8/22/25 IF GPS +3V3 OFF THEN SENSOR I2C BUS DOESN'T WORK. CONSIDER UART ONLY? [GPS POWER ALWAYS ON]
// ***DONE*** SG 10/28/25 ADD 10K PULLDOWN ON TPS63900 ENABLE LINE
// ***DONE*** SG 10/28/25 ADD 10K PULLUP ON SAT_PGOOD (TO 3V3_SAT) [R187 ADDED]
// ***DONE*** SG 10/28/25 CHANGE SLEEP MODE PIN (SAT_PM_2) FROM PB13 TO PB3 ON ARGOS MODULE (CORRESPONDS TO THE DEFAULT SLEEP MODE PIN OF THE ARGOS MODULE). NOTE: REMOVE DBG_SWO NET (WAS PB3)
// *** PUT ON CONNECTOR BOARD***MS 8/5/25 BURN WIRE COMPLETE DETECTION NICE TO HAVE
// ****WAIVED AT DES RVW***SG 5/20/25 CONSIDER I2C CONNECTION TO ARGOS MODULE

// Hardware Configuration

#endif // CETI_WHALE_TAG_VERSIONING_H
