---
name: Test

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    name: Test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/project-ceti/whale-tag-v3-firmware/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build and Run Tests
        run: make test SKIP_GIT=1
