---
name: Test

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Init unity submodule
        run: git submodule update --init --checkout --force lib/unity

      - name: Build and Run Tests 
        run: make test
